"""Orchestrator for the full synthetic data generation pipeline.

Flow:
  1. Generate N body configurations (shape + pose) with body_generator.py
  2. For each body: run SMPL-X forward pass → OBJ + landmarks JSON
  3. Compute ground-truth measurements with measurements_gt.py
  4. Build a manifest JSON listing every (body, view) to render
  5. Launch Blender subprocess to render all entries and write YOLO labels
  6. Write dataset.yaml for YOLO training

Usage:
    python -m pointsx.synthetic.pipeline \
        --n-bodies 500 \
        --model-dir models/smplx \
        --assets-dir assets \
        --out-dir data/synthetic-pose \
        --blender-exe /usr/bin/blender \
        --jobs 4
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
from pathlib import Path

import numpy as np

from pointsx.synthetic.body_generator import (
    generate_body_samples,
    run_smplx_forward,
    save_body_obj,
    save_landmarks_json,
    BodySample,
    NumpyEncoder,
)
from pointsx.synthetic.landmarks import POINTSX16_FLIP_IDX
from pointsx.synthetic.measurements_gt import compute_measurements, sanity_check

logger = logging.getLogger(__name__)


# ── Dataset YAML ─────────────────────────────────────────────────────────────

DATASET_YAML_TEMPLATE = """\
# Auto-generated by PointsX synthetic pipeline
path: {path}
train: train/images
val: val/images

kpt_shape: [16, 3]
flip_idx: {flip_idx}

names:
  0: person
"""


def write_dataset_yaml(out_dir: Path) -> Path:
    flip_str = "[" + ",".join(str(i) for i in POINTSX16_FLIP_IDX) + "]"
    yaml_path = out_dir / "dataset.yaml"
    yaml_path.write_text(
        DATASET_YAML_TEMPLATE.format(path=str(out_dir), flip_idx=flip_str)
    )
    logger.info("Wrote dataset.yaml → %s", yaml_path)
    return yaml_path


# ── SMPL-X phase ─────────────────────────────────────────────────────────────

def run_smplx_phase(
    samples: list[BodySample],
    model_dir: Path,
    out_dir: Path,
) -> list[dict]:
    """Run SMPL-X forward pass for all samples; save OBJ + JSON.

    Returns list of manifest entries (one per sample).
    """
    import smplx  # noqa: F401 — ensure available early

    mesh_dir        = out_dir / "meshes"
    landmarks_dir   = out_dir / "landmarks"
    measurements_dir = out_dir / "measurements"

    mesh_dir.mkdir(parents=True, exist_ok=True)
    landmarks_dir.mkdir(parents=True, exist_ok=True)
    measurements_dir.mkdir(parents=True, exist_ok=True)

    # Load faces + UV layout once (same for every SMPL-X mesh).
    faces = _load_smplx_faces(model_dir)
    uv_data = _load_smplx_uvs(model_dir)
    if uv_data is None:
        logger.warning(
            "No UV layout found in SMPL-X model — exported OBJs will have no UVs "
            "and SMPLitex / photo skin textures won't map correctly."
        )
        uv_verts, uv_faces = None, None
    else:
        uv_verts, uv_faces = uv_data

    from pointsx.synthetic.landmarks import extract_landmarks  # noqa: PLC0415
    from tqdm import tqdm

    manifest_entries = []

    for sample in tqdm(samples, desc="SMPL-X forward pass", unit="body"):
        try:
            vertices, joints, height_m = run_smplx_forward(sample, model_dir)
        except Exception as exc:
            logger.warning("SMPL-X forward pass failed for body %d: %s", sample.body_id, exc)
            continue

        # Update actual height (cast to Python float for JSON serialization)
        sample.actual_height_cm = float(height_m) * 100.0

        # Save OBJ mesh (with UVs when available so SMPLitex textures map correctly)
        obj_path = mesh_dir / f"body_{sample.body_id:05d}.obj"
        save_body_obj(vertices, faces, obj_path, uv_verts=uv_verts, uv_faces=uv_faces)

        # Extract landmarks
        landmarks_3d = extract_landmarks(vertices, joints)

        # Compute measurements
        meas = compute_measurements(vertices, joints, faces, sample.sex)
        warnings = sanity_check(meas)
        if warnings:
            logger.debug("Body %d warnings: %s", sample.body_id, "; ".join(warnings))

        # Save landmarks JSON (includes measurements)
        lm_path = landmarks_dir / f"body_{sample.body_id:05d}.json"
        save_landmarks_json(sample, landmarks_3d, meas.to_dict(), lm_path)

        # Save measurements separately
        meas_path = measurements_dir / f"body_{sample.body_id:05d}.json"
        meas_path.write_text(
            json.dumps({
                "body_id": sample.body_id,
                "sex": sample.sex,
                "actual_height_cm": round(float(sample.actual_height_cm), 1),
                "bmi_class": sample.bmi_class,
                **meas.to_dict(),
            }, indent=2, cls=NumpyEncoder)
        )

        # Pick random skin texture index (1–30)
        skin_idx = (sample.body_id % 30) + 1

        manifest_entries.append({
            "body_id":             sample.body_id,
            "sex":                 sample.sex,
            "bmi_class":           sample.bmi_class,
            "obj_path":            str(obj_path),
            "landmarks_json_path": str(lm_path),
            "skin_texture_idx":    skin_idx,
            "seed":                sample.body_id * 7,
        })

    logger.info("SMPL-X phase complete: %d bodies saved", len(manifest_entries))
    return manifest_entries


def _load_smplx_faces(model_dir: Path) -> np.ndarray:
    """Load triangle face indices from an SMPL-X model file."""
    import smplx

    # Pass the .npz file path directly to bypass smplx's directory resolution
    # (the library double-appends "smplx/" when given a directory).
    model = smplx.create(
        str(model_dir / "SMPLX_NEUTRAL.npz"),
        model_type="smplx",
        gender="neutral",
        use_face_contour=False,
        num_betas=10,
        ext="npz",
    )
    faces = model.faces.astype(np.int32)
    del model
    return faces


def _load_smplx_uvs(model_dir: Path) -> tuple[np.ndarray, np.ndarray] | None:
    """Read SMPL-X UV layout (vt, ft) directly from the .npz model file.

    Returns (uv_verts, uv_faces) where:
        uv_verts: (N_uv, 2) float — u,v coords in [0,1]
        uv_faces: (N_faces, 3) int — index into uv_verts
    Returns None when the model file has no UV info.
    """
    npz_path = model_dir / "SMPLX_NEUTRAL.npz"
    if not npz_path.exists():
        return None
    try:
        data = np.load(str(npz_path), allow_pickle=False)
    except Exception:
        # Some SMPL-X .npz files store pickled objects — retry with allow_pickle.
        data = np.load(str(npz_path), allow_pickle=True)
    if "vt" not in data.files or "ft" not in data.files:
        logger.warning("SMPL-X .npz has no 'vt'/'ft' UV arrays — bodies will render untextured.")
        return None
    return np.asarray(data["vt"], dtype=np.float32), np.asarray(data["ft"], dtype=np.int32)


# ── Blender phase ─────────────────────────────────────────────────────────────

def run_blender_phase(
    manifest: list[dict],
    out_dir: Path,
    assets_dir: Path,
    blender_exe: str,
    jobs: int = 1,
    use_gpu: bool = False,
    mode: str = "photo",
    engine: str | None = None,
) -> None:
    import math
    """Chunk the manifest and launch Blender subprocess(es)."""
    manifest_path = out_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, cls=NumpyEncoder))
    logger.info("Wrote manifest with %d entries → %s", len(manifest), manifest_path)

    blender_script = Path(__file__).with_name("blender_render.py")
    if not blender_script.exists():
        raise FileNotFoundError(f"Blender render script not found: {blender_script}")

    # Split manifest into chunks for parallel Blender instances
    chunk_size = math.ceil(len(manifest) / max(jobs, 1))
    procs = []

    for job_idx in range(jobs):
        start = job_idx * chunk_size
        end   = min(start + chunk_size, len(manifest))
        if start >= len(manifest):
            break

        cmd = [
            blender_exe,
            "--background",
            "--python", str(blender_script),
            "--",
            "--manifest",   str(manifest_path),
            "--out-dir",    str(out_dir),
            "--assets",     str(assets_dir),
            "--mode",       mode,
            "--start-idx",  str(start),
            "--end-idx",    str(end),
        ]
        if engine:
            cmd.extend(["--engine", engine])
        if use_gpu:
            cmd.append("--gpu")

        logger.info(
            "Starting Blender job %d/%d (entries %d–%d)",
            job_idx + 1, jobs, start, end,
        )
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        procs.append((job_idx, proc))

    # Wait and stream output
    for job_idx, proc in procs:
        for line in proc.stdout:
            print(f"[blender-{job_idx}] {line}", end="")
        proc.wait()
        if proc.returncode != 0:
            logger.error("Blender job %d exited with code %d", job_idx, proc.returncode)

    logger.info("All Blender jobs finished.")


# ── Summary stats ─────────────────────────────────────────────────────────────

def print_summary(out_dir: Path) -> None:
    """Print counts of generated images and labels."""
    for split in ("train", "val"):
        imgs   = list((out_dir / split / "images").glob("*.jpg"))
        labels = list((out_dir / split / "labels").glob("*.txt"))
        print(f"  {split}: {len(imgs)} images, {len(labels)} labels")

    meshes = list((out_dir / "meshes").glob("*.obj"))
    meas   = list((out_dir / "measurements").glob("*.json"))
    print(f"  meshes: {len(meshes)}, measurements: {len(meas)}")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="PointsX synthetic data generation pipeline (SMPL-X + Blender)"
    )
    parser.add_argument("--n-bodies",    type=int, default=500,
                        help="Number of unique bodies (each gets 3 pose variants)")
    parser.add_argument("--seed",        type=int, default=42)
    parser.add_argument("--model-dir",   required=True,
                        help="Directory with SMPLX_MALE.npz / SMPLX_FEMALE.npz")
    parser.add_argument("--assets-dir",  required=True,
                        help="Assets: assets/hdri/, assets/textures/, assets/clothing/")
    parser.add_argument("--out-dir",     default="data/synthetic-pose",
                        help="Output root directory")
    parser.add_argument("--blender-exe", default="blender",
                        help="Path to Blender executable")
    parser.add_argument("--jobs",        type=int, default=1,
                        help="Number of parallel Blender instances")
    parser.add_argument("--gpu",         action="store_true",
                        help="Enable GPU rendering in Blender (Cycles CUDA)")
    parser.add_argument("--smplx-only",  action="store_true",
                        help="Only run SMPL-X phase (skip Blender rendering)")
    parser.add_argument("--mode", type=str, default="both",
                        choices=["photo", "mask", "both"],
                        help="'photo' = pose dataset, 'mask' = seg dataset, "
                             "'both' (default) = render both in one run (shares SMPL-X phase)")
    parser.add_argument("--seg-out-dir", default=None,
                        help="Where to write the seg dataset when --mode is 'both' or 'mask'. "
                             "If omitted, defaults to <out-dir>-seg (e.g. synthetic-pose → synthetic-pose-seg).")
    parser.add_argument("--engine", type=str, default=None,
                        choices=["CYCLES", "BLENDER_EEVEE"],
                        help="Render engine (default: script default)")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    out_dir    = Path(args.out_dir)
    model_dir  = Path(args.model_dir)
    assets_dir = Path(args.assets_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Phase 1: Generate body samples ──────────────────────────────────
    logger.info("Generating %d body configurations…", args.n_bodies)
    samples = generate_body_samples(n_bodies=args.n_bodies, seed=args.seed)
    logger.info("Total pose variants: %d", len(samples))

    # ── Phase 2: SMPL-X forward pass ────────────────────────────────────
    logger.info("Running SMPL-X forward pass…")
    manifest = run_smplx_phase(samples, model_dir, out_dir)

    if args.smplx_only:
        logger.info("--smplx-only set; stopping before Blender rendering.")
        print_summary(out_dir)
        return

    # Resolve seg output dir (used by mask + both modes)
    if args.seg_out_dir is not None:
        seg_out_dir = Path(args.seg_out_dir)
    else:
        # Default: sibling "<out>-seg" (e.g. synthetic-pose → synthetic-pose-seg)
        seg_out_dir = out_dir.parent / f"{out_dir.name}-seg"

    modes_to_run: list[tuple[str, Path]] = []
    if args.mode in ("photo", "both"):
        modes_to_run.append(("photo", out_dir))
    if args.mode in ("mask", "both"):
        modes_to_run.append(("mask", seg_out_dir if args.mode == "both" else out_dir))

    # ── Phase 3: Blender rendering ───────────────────────────────────────
    for render_mode, render_out in modes_to_run:
        render_out.mkdir(parents=True, exist_ok=True)
        logger.info(
            "Starting Blender rendering: mode=%s → %s (%d jobs)",
            render_mode, render_out, args.jobs,
        )
        run_blender_phase(
            manifest,
            render_out,
            assets_dir,
            blender_exe=args.blender_exe,
            jobs=args.jobs,
            use_gpu=args.gpu,
            mode=render_mode,
            engine=args.engine,
        )

    # ── Phase 4: Finalize dataset(s) ─────────────────────────────────────
    from pointsx.synthetic.masks_to_polygons import (
        convert_directory,
        write_dataset_yaml as write_seg_yaml,
    )

    for render_mode, render_out in modes_to_run:
        if render_mode == "mask":
            logger.info("Converting silhouette masks → YOLO polygon labels (%s)…", render_out)
            stats = convert_directory(render_out)
            logger.info(
                "Polygons written: ok=%d  empty=%d  skipped=%d  total=%d",
                stats["ok"], stats["empty"], stats["skipped"], stats["total"],
            )
            if stats["ok"] > 0:
                write_seg_yaml(render_out)
        else:
            write_dataset_yaml(render_out)

    # ── Summary ──────────────────────────────────────────────────────────
    for render_mode, render_out in modes_to_run:
        print(f"\n=== Summary ({render_mode}) ===")
        print_summary(render_out)
        print(f"Dataset YAML: {render_out / 'dataset.yaml'}")


if __name__ == "__main__":
    main()
