// Vercel static-build step for PointsX.
//
// The frontend lives in src/webui/static/. The SPA's HTML/JS reference
// assets at `/static/...` (because in the single-container HF deployment
// FastAPI mounts that folder at /static). On Vercel we mirror that layout:
//
//   public/
//     index.html                ← copied from src/webui/static/index.html
//     static/                   ← copied from src/webui/static/ (everything)
//       config.js               ← OVERWRITTEN with the runtime POINTSX_API_BASE
//       js/...
//       css/...
//
// Required env var on Vercel:
//   POINTSX_API_BASE   e.g. https://your-username-pointsx.hf.space

import { cp, mkdir, writeFile, copyFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "src", "webui", "static");
const OUT = path.join(ROOT, "public");
const OUT_STATIC = path.join(OUT, "static");

const apiBase = (process.env.POINTSX_API_BASE || "").replace(/\/+$/, "");

await mkdir(OUT, { recursive: true });
await mkdir(OUT_STATIC, { recursive: true });

// 1. Copy everything from src/webui/static/ into public/static/
await cp(SRC, OUT_STATIC, { recursive: true });

// 2. Promote index.html to the site root
await copyFile(path.join(SRC, "index.html"), path.join(OUT, "index.html"));

// 3. Overwrite config.js with the runtime API base (POINTSX_API_BASE env var)
const configJs = [
  "// AUTO-GENERATED by scripts/build_static.mjs at Vercel build time.",
  "// Edit POINTSX_API_BASE in the Vercel project's env vars to change.",
  `window.POINTSX_API_BASE = ${JSON.stringify(apiBase)};`,
  "",
].join("\n");
await writeFile(path.join(OUT_STATIC, "config.js"), configJs, "utf-8");

console.log(`build_static: src=${SRC}`);
console.log(`build_static: out=${OUT}`);
console.log(`build_static: POINTSX_API_BASE=${apiBase || "(empty — same-origin)"}`);
